static void testFridgeInventory() {
  assert(uiCanvasInit());clockInit();screensInit();
  assert(!clockIsSet());
  fridge::reset(fridgeData);
  fridgeData.items[0]={5,1,7};fridgeData.items[5]={8,0,2};
  for(uint8_t i=1;i<5;++i) fridgeData.items[i]={static_cast<uint8_t>(i+10),i,i};
  assert(fridgeSave());
  const auto original=fridgeData;
  const auto protectedBefore=protectedFiles();
  enter(SCR_FRIDGE);
  assert(foodIndex==0&&foodColumn==FOOD_NAME);
  tft.snapshot("artifacts/fridge-inventory/select_native.json");
  press(UI_UP);assert(foodIndex==0);
  press(UI_DOWN);assert(foodIndex==5);press(UI_DOWN);assert(foodIndex==5);
  press(UI_UP);press(UI_RIGHT);
  assert(curScreen()==SCR_FRIDGE&&foodIndex==0&&foodColumn==FOOD_STOCK&&foodValue==5);
  press(UI_DOWN);press(UI_DOWN);
  assert(foodValue==3&&foodIndex==0&&fridgeData.items[0].stock==5&&fridgeData.items[0].eaten==1);
  tft.snapshot("artifacts/fridge-inventory/edit_native.json");
  press(UI_UP);press(UI_OK);
  assert(foodColumn==FOOD_NAME&&fridgeData.items[0].stock==4&&fridgeData.items[0].eaten==2);
  assert(fridgeData.items[0].incoming==7);
  press(UI_RIGHT);press(UI_UP);press(UI_UP);press(UI_OK);
  assert(fridgeData.items[0].stock==6&&fridgeData.items[0].eaten==2);
  const auto saved=fridgeData;const auto files=fakeFiles;
  press(UI_RIGHT);press(UI_DOWN);press(UI_LEFT);
  assert(foodColumn==FOOD_NAME&&fakeFiles==files);
  press(UI_RIGHT);press(UI_DOWN);press(UI_BACK);
  assert(foodColumn==FOOD_NAME&&fakeFiles==files);
  press(UI_RIGHT);press(UI_OK);
  assert(foodColumn==FOOD_NAME&&fakeFiles==files);
  press(UI_RIGHT);press(UI_DOWN);press(UI_RIGHT);
  assert(foodColumn==FOOD_EATEN&&fakeFiles==files);
  press(UI_RIGHT);assert(foodColumn==FOOD_EATEN);
  press(UI_DOWN);assert(foodIndex==5&&foodColumn==FOOD_EATEN);
  press(UI_LEFT);assert(foodValue==8&&foodColumn==FOOD_STOCK);
  press(UI_DOWN);press(UI_OK);
  assert(fridgeData.items[5].stock==7&&fridgeData.items[5].eaten==1);
  assert(fridge::sameItem(saved.items[0],fridgeData.items[0]));
  std::cout<<"PASS rows/columns, net reduction, restock, cancel, no-op and item isolation"<<std::endl;

  press(UI_UP);press(UI_RIGHT);press(UI_DOWN);
  const auto beforeFailure=fridgeData;
  failWrites=true;press(UI_OK);failWrites=false;
  assert(!fridgeLastSaveOk&&foodColumn==FOOD_STOCK&&foodValue==5);
  assert(std::memcmp(&beforeFailure,&fridgeData,sizeof fridgeData)==0);
  fridgeLoad();assert(fridgeData.items[0].stock==6&&fridgeData.items[0].eaten==2);
  press(UI_OK);assert(fridgeLastSaveOk&&fridgeData.items[0].stock==5&&fridgeData.items[0].eaten==3);
  const auto committed=fridgeData;fridgeLoad();
  assert(std::memcmp(&committed,&fridgeData,sizeof committed)==0);
  for(uint8_t i=1;i<5;++i) assert(fridge::sameItem(original.items[i],fridgeData.items[i]));
  assert(sizeof(fridgeData)==48&&protectedFiles()==protectedBefore);
  std::cout<<"PASS failed-save rollback/retry, reload, hidden food preservation and 48-byte compatibility"<<std::endl;

  fridgeData.items[0]={0,0,0};assert(fridgeSave());
  press(UI_RIGHT);press(UI_DOWN);assert(foodValue==0);press(UI_BACK);
  fridgeData.items[0]={99,98,0};assert(fridgeSave());
  press(UI_RIGHT);press(UI_UP);assert(foodValue==99);
  press(UI_DOWN);press(UI_DOWN);
  const auto beforeOverflow=fridgeData;const auto overflowFiles=fakeFiles;
  press(UI_OK);
  assert(foodColumn==FOOD_STOCK&&fakeFiles==overflowFiles);
  assert(std::memcmp(&beforeOverflow,&fridgeData,sizeof fridgeData)==0);
  press(UI_UP);press(UI_OK);assert(fridgeData.items[0].stock==98&&fridgeData.items[0].eaten==99);
  press(UI_RIGHT);press(UI_UP);press(UI_OK);
  assert(fridgeData.items[0].stock==99&&fridgeData.items[0].eaten==99);
  fridge::Item ignored={0,0,0};
  assert(fridge::previewInventory(fridgeData,6,0,ignored)==fridge::BAD_VALUE);
  assert(fridge::previewInventory(fridgeData,0,100,ignored)==fridge::BAD_VALUE);
  std::cout<<"PASS stock 0/99 and eaten overflow atomic rejection; restock at eaten limit"<<std::endl;

  fridgeData.items[0]={5,1,0};fridgeData.date=20261002;
  memset(&fridgeData.undo,0,sizeof fridgeData.undo);assert(fridgeSave());
  const auto beforeClock=fridgeData;
  press(UI_RIGHT);press(UI_DOWN);assert(foodValue==4);
  clockSet(1790956800);tick();
  assert(std::memcmp(&beforeClock,&fridgeData,sizeof fridgeData)==0&&foodValue==4);
  clockSet(1791043200);tick();press(UI_OK);
  assert(fridgeData.items[0].stock==4&&fridgeData.items[0].eaten==2&&fridgeData.date==20261002);
  const auto beforeInit=fridgeData;orchardInit();
  assert(std::memcmp(&beforeInit,&fridgeData,sizeof fridgeData)==0);
  std::cout<<"PASS uncalibrated editing, clock set/date change, single confirmation and boot preservation"<<std::endl;

  enter(SCR_TREE);enter(SCR_FRIDGE);press(UI_DOWN);press(UI_RIGHT);press(UI_DOWN);
  const auto draft=foodValue;const auto beforeTimer=fridgeData;
  press(UI_FARM);assert(curScreen()==SCR_TIMER);press(UI_TIMER);
  assert(curScreen()==SCR_FRIDGE&&foodIndex==5&&foodColumn==FOOD_STOCK&&foodValue==draft);
  timer.setMinutes(1);timer.toggle(fakeMillis);fakeMillis+=61000;orchardTick();
  assert(curScreen()==SCR_ALERT);press(UI_OK);
  assert(curScreen()==SCR_FRIDGE&&foodIndex==5&&foodColumn==FOOD_STOCK&&foodValue==draft);
  assert(std::memcmp(&beforeTimer,&fridgeData,sizeof fridgeData)==0);
  press(UI_TIMER);assert(curScreen()==SCR_TREE);press(UI_FARM);
  assert(curScreen()==SCR_FRIDGE&&foodIndex==0&&foodColumn==FOOD_NAME);
  press(UI_RIGHT);press(UI_UP);press(UI_FARM);press(UI_FARM);
  assert(curScreen()==SCR_TODAY&&!foodTimerContext);
  enter(SCR_FRIDGE);assert(foodColumn==FOOD_NAME&&foodIndex==0);
  assert(curScreen()==SCR_FRIDGE&&foodColumn==FOOD_NAME);
  assert(protectedFiles()==protectedBefore);
  std::cout<<"PASS timer/alert draft restoration and normal navigation cancellation"<<std::endl;
}
